const labels={relationship:'关系与日常',continuity:'记忆与延续',practice:'技术与部署',creation:'共同创作'};
const list=document.querySelector('#postList'),dialog=document.querySelector('#post-dialog'),rules=document.querySelector('#rules-dialog'),form=document.querySelector('#post-form'),submit=form.querySelector('button[type="submit"]'),feedback=form.querySelector('.form-feedback'),toast=document.querySelector('#community-toast');let filter='latest',category='';
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node}
function date(value){return new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}
function show(message){toast.textContent=message;toast.hidden=false;setTimeout(()=>{toast.hidden=true},3500)}
function render(threads){list.replaceChildren();if(!threads.length){list.append(el('p','community-state','这里还没有帖子。写下第一篇，让房间真正有人停留。'));return}for(const thread of threads){const link=el('a','post-link');link.href=`./thread/?id=${encodeURIComponent(thread.id)}`;const article=el('article','post'),time=el('div','post-time');time.append(document.createTextNode(date(thread.created_at)),document.createElement('br'),document.createTextNode(thread.nickname));const copy=document.createElement('div');copy.append(el('h2','post-title',thread.title),el('p','post-summary',thread.summary));const tags=el('div','post-tags');tags.append(el('span',`tag ${thread.category==='relationship'?'relation':thread.category==='practice'?'tech':''}`,labels[thread.category]||thread.category));copy.append(tags);article.append(time,copy,el('div','post-stats',`${Number(thread.reply_count||0)} 回复`));link.append(article);list.append(link)}}
async function load(){list.replaceChildren(el('p','community-state','正在读取讨论…'));const params=new URLSearchParams({filter});if(category)params.set('category',category);try{const response=await fetch(`/api/community/threads?${params}`),data=await response.json();if(response.status===401){location.href='/community/login/';return}if(!response.ok)throw new Error(data.error||'读取失败。');render(data.threads||[])}catch(error){list.replaceChildren(el('p','community-state post-error',error.message))}}
async function me(){const response=await fetch('/api/community/auth/me'),data=await response.json();if(!response.ok){location.href='/community/login/';return}document.querySelector('#community-user').textContent=data.user.username}
document.querySelectorAll('[data-action="open-post"]').forEach(button=>button.addEventListener('click',()=>dialog.showModal()));document.querySelectorAll('[data-action="open-rules"]').forEach(button=>button.addEventListener('click',()=>rules.showModal()));document.querySelectorAll('[data-close-dialog]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));document.querySelectorAll('dialog').forEach(item=>item.addEventListener('click',event=>{if(event.target===item)item.close()}));
document.querySelectorAll('.filter-btn').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter-btn').forEach(item=>item.classList.remove('active'));button.classList.add('active');filter=button.dataset.filter||'latest';category=button.dataset.category||'';load()}));document.querySelectorAll('.category[data-category]').forEach(button=>button.addEventListener('click',()=>{category=button.dataset.category;filter='latest';document.querySelectorAll('.filter-btn').forEach(item=>item.classList.toggle('active',item.dataset.category===category));load()}));
form.addEventListener('submit',async event=>{event.preventDefault();submit.disabled=true;feedback.textContent='正在发布…';const data=new FormData(form);try{const response=await fetch('/api/community/threads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({category:data.get('category'),title:data.get('title'),content:data.get('content')})}),result=await response.json();if(!response.ok)throw new Error(result.error||'发布失败。');form.reset();dialog.close();show(result.message);await load()}catch(error){feedback.textContent=error.message}finally{submit.disabled=false}});
document.querySelector('[data-action="logout"]').addEventListener('click',async()=>{await fetch('/api/community/auth/logout',{method:'POST'});location.href='/community/login/'});
me();load();
